basePath: /api
info:
  contact:
    email: ChnMig@Outlook.com
    name: ChnMig
  description: Gshop is an API for shopping websites
  license:
    name: Apache 2.0
    url: https://github.com/ChnMig/gshop/blob/main/LICENSE
  title: Gshop API
  version: "0.1"
paths: {}
swagger: "2.0"
